### ISSUE TITLE
Infinite loop when trying to import a banner for a new game

### ISSUE THREAD

**Issue by luontola** [finol-digital/Card-Game-Simulator#90] opened 2023-05-10 19:32 UTC
When trying to import a banner image for a game, the file open dialog keeps popping up indefinitely regardless of whether you select an image or press cancel. The app must be terminated from Task Manager to exit the loop.

**To Reproduce**
1. Click the "+" in the main screen to create a game
2. Click the "+" in the Banner section
3. Choose an image and press "Open", or press "Cancel"

**Expected behavior**
The file open dialog is closed.

**Actual behavior**
The file open dialog pops up again and again, indefinitely. The title of the dialog is "Select Card Back Image File" and chosing an image changes the Card Back, even though I clicked the button for importing a Banner. Seems like the first time the dialog pops up, it changes the Banner, but on following dialogs it changes the Card Back.

**Desktop:**
 - OS: Windows
 - Steam
 - Version 1.83

**Comment by davidmfinol** [comment] 2023-05-12 22:21
Thanks for reporting this! 
Is it on Windows 10 or Windows 11?
Any chance you could take a video and share?
I tried it on my Windows 11 PC and couldn't replicate: https://youtu.be/uEvlEg9WijI

Sharing the Player.log log file from `%userprofile%\appdata\locallow\Finol Digital LLC\Card Game Simulator` would also help with finding root cause.
Thank you!

**Comment by davidmfinol** [comment] 2023-07-06 15:12
Closing since unable to reproduce.

**Closed as completed by davidmfinol** 2023-07-06 15:12 UTC
